### ISSUE TITLE
No option on menu

### ISSUE THREAD

**Issue by gena-snow** [Raicuparta/ow-spawn-points#4] opened 2021-04-05 12:56 UTC
When the game first launches, I get these errors:
NullReferenceException: Object reference not set to an instance of an object. Stack trace: OWSpawnPoints.OWSpawnPoints.Init () <0x00129> OWSpawnPoints.OWSpawnPoints.OnEvent (UnityEngine.MonoBehaviour,OWML.Common.Events) <0x00056> OWML.ModHelper.Events.ModEvents.OnPatchEvent (UnityEngine.MonoBehaviour,OWML.Common.Events) <0x0012e> OWML.ModHelper.Events.Patches.AfterStart (UnityEngine.MonoBehaviour) <0x0003d> (wrapper dynamic-method) Flashlight.Start_Patch1 (object) <0x00090>

Later, at some random point in time, I got this:
NullReferenceException. Stack trace: UnityEngine.Object.Instantiate<UnityEngine.UI.Button> (UnityEngine.UI.Button) <0x00043> OWML.ModHelper.Menus.ModButtonBase.Copy () <0x00032> OWML.ModHelper.Menus.ModButtonBase.Duplicate () <0x0001c> OWML.ModHelper.Menus.ModTitleButton.Duplicate (string) <0x00027> OWSpawnPoints.OWSpawnPoints.Init () <0x0013b> OWSpawnPoints.OWSpawnPoints.OnEvent (UnityEngine.MonoBehaviour,OWML.Common.Events) <0x00056> OWML.ModHelper.Events.ModEvents.OnPatchEvent (UnityEngine.MonoBehaviour,OWML.Common.Events) <0x0012e> OWML.ModHelper.Events.Patches.AfterStart (UnityEngine.MonoBehaviour) <0x0003d> (wrapper dynamic-method) Flashlight.Start_Patch1 (object) <0x00090>

The option to teleport never appeared on the pause menu.

**Comment by guich38** [comment] 2021-07-05 22:22
Same here, the "Teleport to" menu which should be displayed in the pause menu isn't accessible:

NullReferenceException: Object reference not set to an instance of an object. Stack trace: OWSpawnPoints.OWSpawnPoints.Init () <0x00129> OWSpawnPoints.OWSpawnPoints.OnEvent (UnityEngine.MonoBehaviour,OWML.Common.Events) <0x00056> OWML.ModHelper.Events.ModEvents.OnPatchEvent (UnityEngine.MonoBehaviour,OWML.Common.Events) <0x0012e> OWML.ModHelper.Events.Patches.AfterStart (UnityEngine.MonoBehaviour) <0x0003d> (wrapper dynamic-method) Flashlight.Start_Patch1 (object) <0x00090>

**Comment by Raicuparta** [comment] 2021-07-05 22:24
This is a known issue with OWML, only on the Steam version, sorry.

**Comment by parkerault** [comment] 2021-08-11 04:11
So is this just unusable on steam or is there a workaround, or a potential fix?

**Comment by Raicuparta** [comment] 2021-08-11 09:21
Unusable on Steam yes. Will probably never be fixed. I'll add a warning to the mod's readme.

**Comment by Raicuparta** [comment] 2021-08-11 09:21
Closing as duplicate of #1

**Closed as completed by Raicuparta** 2021-08-11 09:21 UTC
